"use client";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { apiFetch, billingApi } from "@/lib/api";

type Plan = { id: string; name: string; priceMonthly?: number | null; currency?: string; monthlyMinutes?: number | null; includedPhoneNumbers?: number | null; checkoutAvailable?: boolean; contactSales?: boolean };
const money = (p: Plan) => typeof p.priceMonthly === "number" ? new Intl.NumberFormat("en-US", { style: "currency", currency: p.currency || "USD" }).format(p.priceMonthly) : "Contact sales";
export default function BillingPlans() {
  const params = useSearchParams(); const [plans, setPlans] = useState<Plan[]>([]); const [selected, setSelected] = useState<Plan | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [checkout, setCheckout] = useState(false);
  useEffect(() => { apiFetch<{ plans: Plan[] }>("/billing/plans").then(v => { const available = (v.plans || []).filter(p => ["starter","growth","scale"].includes(p.id)); setPlans(available); const requested = params.get("plan"); if (requested) setSelected(available.find(p => p.id === requested) || null); }).catch(() => setError("Plans are unavailable. Please retry.")).finally(() => setLoading(false)); }, [params]);
  async function continueCheckout() { if (!selected || !selected.checkoutAvailable) return; setCheckout(true); setError(""); try { const result = await billingApi.subscribe(selected.id); const url = result.checkoutUrl || result.url; if (!url) throw new Error("Checkout unavailable"); window.location.assign(url); } catch { setError("Secure checkout is unavailable. Please retry."); setCheckout(false); } }
  return <main className="mx-auto w-full max-w-6xl space-y-8 text-ink"><header className="border-b border-line/40 pb-7"><span className="font-mono text-[10px] uppercase tracking-[0.16em] text-ink-tertiary">Subscription</span><h1 className="mt-2 text-3xl font-bold tracking-tight">Choose a plan</h1><p className="mt-2 text-sm text-ink-secondary">Select a subscription to activate your Bavio workspace.</p></header>{loading ? <p role="status">Loading plans…</p> : error ? <div role="alert" className="border-y border-line py-8"><p>{error}</p><button className="mt-4 min-h-10 border border-line px-4 text-xs font-semibold" onClick={() => window.location.reload()}>Retry</button></div> : <><div className="grid gap-4 md:grid-cols-3">{plans.map(plan => <article key={plan.id} className={`flex flex-col border p-5 ${selected?.id === plan.id ? "border-saffron ring-1 ring-saffron" : "border-line"}`}><h2 className="text-xl font-semibold">{plan.name}</h2><p className="mt-3 text-2xl font-bold">{money(plan)}<small className="ml-1 text-xs font-normal text-ink-tertiary">{typeof plan.priceMonthly === "number" ? "/ month" : ""}</small></p><dl className="mt-6 space-y-3 border-t border-line pt-4 text-xs"><div className="flex justify-between gap-4"><dt className="text-ink-tertiary">Included minutes</dt><dd>{typeof plan.monthlyMinutes === "number" ? plan.monthlyMinutes.toLocaleString() : "Unavailable"}</dd></div><div className="flex justify-between gap-4"><dt className="text-ink-tertiary">Phone numbers</dt><dd>{typeof plan.includedPhoneNumbers === "number" ? plan.includedPhoneNumbers : "Unavailable"}</dd></div></dl><button disabled={!plan.checkoutAvailable} onClick={() => setSelected(plan)} className="mt-7 min-h-10 border border-line px-3 text-xs font-semibold disabled:cursor-not-allowed disabled:opacity-50">{plan.checkoutAvailable ? `Choose ${plan.name}` : "Checkout unavailable"}</button></article>)}</div>{selected && <section className="border-y border-line py-6" aria-labelledby="review-selection"><h2 id="review-selection" className="text-sm font-bold uppercase tracking-wider">Review selection</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-4"><div><dt className="text-xs text-ink-tertiary">Plan</dt><dd>{selected.name}</dd></div><div><dt className="text-xs text-ink-tertiary">Billing cycle</dt><dd>Monthly</dd></div><div><dt className="text-xs text-ink-tertiary">Included minutes</dt><dd>{selected.monthlyMinutes?.toLocaleString() || "Unavailable"}</dd></div><div><dt className="text-xs text-ink-tertiary">Amount</dt><dd>{money(selected)}</dd></div></dl><p className="mt-4 text-xs text-ink-tertiary">Payments securely processed by Dodo Payments.</p><button disabled={checkout} onClick={() => void continueCheckout()} className="mt-5 min-h-11 bg-saffron px-5 text-xs font-semibold text-white">{checkout ? "Opening secure checkout…" : "Continue to secure checkout →"}</button></section>}</>}</main>;
}