'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { ArrowRight, CheckCircle, Circle, GitFork, Warning, XCircle } from '@phosphor-icons/react';
import { WorkflowDefinition, WorkflowExecutionDetail, WorkflowRun, WorkflowStepExecution, WorkflowStatus, workflowsApi } from '@/lib/api';

const formatDate = (value?: string | null) => value ? new Date(value).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }) : 'Time unavailable';
const workflowPath = (id: string) => `/dashboard/workflows/${encodeURIComponent(id)}`;
const executionPath = (id: string) => `/dashboard/workflows/executions/${encodeURIComponent(id)}`;
const stepSummary = (workflow: WorkflowDefinition) => workflow.steps.map(step => step.name).join(' → ');
const displayTrigger = (workflow: WorkflowDefinition) => workflow.trigger || 'Unavailable';
const displaySource = (run: WorkflowRun) => run.source_type && !run.source_type.startsWith('stage8_') ? run.source_type : 'Unavailable';
const humanFailure = (message?: string | null) => message?.replace(/^Webhook delivery failed\.$/, 'Webhook delivery failed.') || 'Workflow failed.';

function Status({ status, compact = false }: { status: WorkflowStatus | 'skipped' | 'available' | 'disabled'; compact?: boolean }) {
  const labels: Record<string, string> = { succeeded: 'Succeeded', failed: 'Failed', partial: 'Partial', running: 'Processing', pending: 'Processing', processing: 'Processing', unknown: 'Unknown', skipped: 'Skipped', available: 'Available', disabled: 'Disabled', unavailable: 'Unavailable' };
  const good = status === 'succeeded' || status === 'available';
  const bad = status === 'failed' || status === 'disabled';
  const tone = good ? 'text-state-success' : bad ? 'text-state-error' : status === 'skipped' ? 'text-ink-muted' : 'text-ink-secondary';
  return <span className={`inline-flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[0.12em] ${tone}`}><Circle weight="fill" size={compact ? 6 : 7} aria-hidden="true" />{labels[status] || status}</span>;
}

function ErrorState({ message, onRetry }: { message: string; onRetry?: () => void }) {
  return <div role="alert" className="border border-state-error/30 bg-surface p-6 text-sm text-state-error">{message}{onRetry && <button onClick={onRetry} className="ml-4 font-semibold underline">Retry</button>}</div>;
}

function WorkflowRow({ workflow }: { workflow: WorkflowDefinition }) {
  return <Link href={workflowPath(workflow.id)} className="group grid gap-3 border-t border-line px-1 py-4 first:border-t-0 hover:bg-surface-raised/30 sm:px-2 md:grid-cols-[minmax(260px,1.5fr)_minmax(140px,.7fr)_minmax(100px,.4fr)_minmax(140px,.7fr)_minmax(140px,.7fr)_auto] md:items-center">
    <div className="flex min-w-0 items-start gap-3"><span className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-line-subtle bg-canvas text-ink-secondary"><GitFork size={17} aria-hidden="true" /></span><span className="min-w-0"><strong className="block truncate text-sm font-semibold text-ink">{workflow.name}</strong><small className="mt-1 block truncate text-xs text-ink-tertiary">{stepSummary(workflow)}</small></span></div>
    <span className="text-xs text-ink-secondary"><span className="block font-mono text-[9px] uppercase tracking-wider text-ink-muted">Steps</span>{workflow.steps.length} steps</span>
    <span className="text-xs text-ink-secondary"><span className="block font-mono text-[9px] uppercase tracking-wider text-ink-muted">Version</span>v{workflow.version}</span>
    <span className="text-xs text-ink-secondary"><span className="block font-mono text-[9px] uppercase tracking-wider text-ink-muted">Trigger</span>{displayTrigger(workflow)}</span><span><span className="mb-1 block font-mono text-[9px] uppercase tracking-wider text-ink-muted">Status</span><Status status={workflow.enabled ? 'available' : 'disabled'} /></span>
    <span className="flex items-center justify-between gap-4 text-xs text-ink-tertiary"><span><span className="block font-mono text-[9px] uppercase tracking-wider text-ink-muted">Last run</span>{workflow.last_run ? formatDate(workflow.last_run.started_at) : 'No runs yet'}</span><ArrowRight className="text-ink-muted transition-transform group-hover:translate-x-1 group-hover:text-saffron" size={18} aria-hidden="true" /></span>
  </Link>;
}

function StepPath({ steps }: { steps: { position: number; name: string; action_type: string; system: string; kind: string }[] }) {
  return <div className="relative ml-1 space-y-7 before:absolute before:bottom-3 before:left-3.5 before:top-3 before:w-px before:bg-line">{steps.map((step, index) => <div key={step.position} className="relative grid grid-cols-[1.75rem_minmax(0,1fr)] gap-3"><span className="relative z-10 flex h-7 w-7 items-center justify-center rounded-full border border-line bg-canvas font-mono text-[10px] font-bold text-ink-secondary">{String(step.position).padStart(2, '0')}</span><div className="min-w-0"><p className="text-sm font-semibold text-ink">{step.name}</p><p className="mt-1 text-xs text-ink-secondary">{step.system} · {step.kind} action</p><p className="mt-2 font-mono text-[10px] text-ink-muted">{step.action_type}</p>{index < steps.length - 1 && <p className="mt-5 text-[10px] font-semibold uppercase tracking-[0.14em] text-ink-muted">On success</p>}</div></div>)}</div>;
}

function RunRow({ run }: { run: WorkflowRun }) {
  return <Link href={executionPath(run.id)} className="group grid grid-cols-[minmax(0,1fr)_auto] gap-3 border-t border-line py-3.5 first:border-t-0 md:grid-cols-[minmax(0,1.2fr)_minmax(110px,.6fr)_minmax(150px,.8fr)_minmax(150px,.8fr)_auto] md:items-center"><span className="min-w-0"><strong className="block truncate font-mono text-xs font-medium text-ink">{run.id.slice(0, 12)}…</strong><small className="mt-1 block text-xs text-ink-tertiary">Version {run.version} · {displaySource(run)}</small></span><Status status={run.status} compact /><span className="hidden text-xs text-ink-tertiary md:block"><small className="mb-1 block font-mono text-[9px] uppercase tracking-wider text-ink-muted">Started</small>{formatDate(run.started_at || run.created_at)}</span><span className="hidden text-xs text-ink-tertiary md:block"><small className="mb-1 block font-mono text-[9px] uppercase tracking-wider text-ink-muted">Ended</small>{formatDate(run.completed_at)}</span><span className="hidden text-xs text-ink-tertiary md:block">{run.failure_step ? `Failed at ${run.failure_step}` : '—'}</span><ArrowRight className="mt-1 text-ink-muted transition-transform group-hover:translate-x-1 group-hover:text-saffron" size={17} aria-hidden="true" /></Link>;
}

function Loading({ detail = false }: { detail?: boolean }) { return <div className="mx-auto w-full max-w-6xl animate-pulse space-y-8"><div><div className="h-3 w-24 rounded bg-surface-raised" /><div className="mt-3 h-10 w-72 rounded bg-surface-raised" /><div className="mt-3 h-4 w-96 max-w-full rounded bg-surface-raised" /></div><div className={`border-y border-line bg-surface/50 ${detail ? 'h-72' : 'h-40'}`} /></div>; }

export default function WorkflowsView() {
  const [workflows, setWorkflows] = useState<WorkflowDefinition[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setError(null); setWorkflows((await workflowsApi.list()).workflows); } catch (err) { setError(err instanceof Error ? err.message : 'Workflow data is unavailable.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <Loading />;
  if (error) return <div className="mx-auto w-full max-w-6xl"><ErrorState message={error} onRetry={() => { setLoading(true); void load(); }} /></div>;
  return <div className="mx-auto w-full max-w-6xl space-y-9"><header><span className="font-mono text-[10px] font-semibold uppercase tracking-[0.18em] text-ink-tertiary">Build / Workflows</span><h1 className="mt-2 font-display text-4xl font-extrabold tracking-tight text-ink md:text-[2.75rem]">Workflows</h1><p className="mt-3 max-w-xl text-sm leading-6 text-ink-secondary">Inspect verified workflows and their execution history.</p></header><section aria-labelledby="workflow-register-heading"><div className="mb-3"><h2 id="workflow-register-heading" className="text-xs font-bold uppercase tracking-[0.16em] text-ink">Workflow register</h2><p className="mt-1 text-xs text-ink-tertiary">Verified workflows available to this workspace.</p></div><div className="border-y border-line">{workflows.length ? workflows.map(workflow => <WorkflowRow key={workflow.id} workflow={workflow} />) : <div className="py-12 text-center text-sm text-ink-tertiary">No workflows available.</div>}</div></section></div>;
}

export function WorkflowDetailView({ id }: { id: string }) {
  const [workflow, setWorkflow] = useState<WorkflowDefinition | null>(null); const [runs, setRuns] = useState<WorkflowRun[]>([]); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setError(null); const [detail, history] = await Promise.all([workflowsApi.detail(id), workflowsApi.executions(id)]); setWorkflow(detail.workflow); setRuns(history.executions); } catch (err) { setError(err instanceof Error ? err.message : 'Workflow detail is unavailable.'); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  if (error) return <div className="mx-auto w-full max-w-5xl"><ErrorState message={error} onRetry={() => void load()} /></div>;
  if (!workflow) return <Loading detail />;
  return <div className="mx-auto w-full max-w-5xl space-y-9"><Link href="/dashboard/workflows" className="inline-flex items-center gap-2 text-xs font-semibold text-ink-secondary hover:text-ink"><ArrowRight className="rotate-180" size={15} />All workflows</Link><header className="border-b border-line pb-7"><div className="flex flex-wrap items-center gap-3"><span className="font-mono text-[10px] font-semibold uppercase tracking-[0.18em] text-ink-tertiary">Workflow</span><Status status={workflow.enabled ? 'available' : 'disabled'} /></div><h1 className="mt-3 font-display text-3xl font-extrabold tracking-tight text-ink md:text-4xl">{workflow.name}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-ink-secondary">Creates a Lead in Bavio, then sends a verified webhook.</p><div className="mt-5 flex flex-wrap gap-x-6 gap-y-2 text-xs text-ink-secondary"><span>Version {workflow.version}</span><span>{workflow.steps.length} steps</span><span>{workflow.enabled ? 'Available' : 'Disabled'}</span></div></header><section aria-labelledby="workflow-steps-heading" className="space-y-5"><div><h2 id="workflow-steps-heading" className="text-xs font-bold uppercase tracking-[0.16em] text-ink">Ordered steps</h2><p className="mt-1 text-xs text-ink-tertiary">If a step fails, later steps do not run. Completed earlier steps are preserved.</p></div><StepPath steps={workflow.steps} /></section><section aria-labelledby="workflow-runs-heading"><div className="mb-3"><h2 id="workflow-runs-heading" className="text-xs font-bold uppercase tracking-[0.16em] text-ink">Recent runs</h2><p className="mt-1 text-xs text-ink-tertiary">Inspect persisted execution history for this workflow.</p></div><div className="border-y border-line">{runs.length ? runs.map(run => <RunRow key={run.id} run={run} />) : <div className="py-10 text-center"><p className="text-sm text-ink-tertiary">No workflow runs yet.</p><p className="mt-1 text-xs text-ink-muted">Verified execution history will appear here after this workflow runs.</p></div>}</div></section></div>;
}

function StepStatusIcon({ status }: { status: WorkflowStepExecution['status'] }) { return status === 'succeeded' ? <CheckCircle className="text-state-success" size={19} weight="fill" aria-hidden="true" /> : status === 'failed' ? <XCircle className="text-state-error" size={19} weight="fill" aria-hidden="true" /> : status === 'skipped' ? <Circle className="text-ink-muted" size={19} weight="fill" aria-hidden="true" /> : <Circle className="text-ink-secondary" size={19} aria-hidden="true" />; }

function TraceStep({ step, previousStepName }: { step: WorkflowStepExecution; previousStepName?: string }) {
  const evidence = step.evidence; const failedMessage = step.failure_message || step.action_error_message;
  return <div className="relative pb-8 last:pb-0"><div className="absolute -left-[2.35rem] top-0 flex h-7 w-7 items-center justify-center rounded-full border border-line bg-canvas"><StepStatusIcon status={step.status} /></div><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-ink-muted">Step {String(step.position).padStart(2, '0')}</p><h3 className="mt-1 text-sm font-semibold text-ink">{step.name}</h3><p className="mt-1 font-mono text-[10px] text-ink-tertiary">{step.action_type}</p></div><Status status={step.status} compact /></div><div className="mt-4 grid gap-4 border-t border-line pt-3 sm:grid-cols-2">{step.status === 'skipped' ? <div className="sm:col-span-2"><span className="font-mono text-[9px] uppercase tracking-wider text-ink-muted">Not run</span><p className="mt-1 text-xs text-ink-secondary">{previousStepName ? `Not run because ${previousStepName} failed.` : 'Not run because an earlier step failed.'}</p></div> : failedMessage ? <div><span className="block font-mono text-[9px] uppercase tracking-wider text-ink-muted">Failure</span><p className="mt-1 text-xs text-state-error">{humanFailure(failedMessage)}</p>{step.failure_code && <p className="mt-2 text-[10px] text-ink-muted">Technical details · {step.failure_code}</p>}</div> : evidence?.http_status ? <div><span className="block font-mono text-[9px] uppercase tracking-wider text-ink-muted">Evidence</span><p className="mt-1 text-xs text-ink">HTTP {evidence.http_status}{evidence.outcome ? ` · ${evidence.outcome}` : ''}</p></div> : evidence?.record_id ? <div><span className="block font-mono text-[9px] uppercase tracking-wider text-ink-muted">Evidence</span><p className="mt-1 truncate font-mono text-xs text-ink" title={evidence.record_id}>Lead ID {evidence.record_id}</p></div> : <p className="text-xs text-ink-tertiary">No evidence recorded.</p>}{step.action_execution_id && <div><span className="block font-mono text-[9px] uppercase tracking-wider text-ink-muted">Action execution</span><Link href={`/dashboard/actions/executions/${step.action_execution_id}`} className="mt-1 inline-flex items-center gap-1 text-xs font-semibold text-saffron hover:underline">Open execution <ArrowRight size={13} /></Link></div>}</div></div>;
}

export function WorkflowExecutionView({ id }: { id: string }) {
  const [data, setData] = useState<WorkflowExecutionDetail | null>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setError(null); setData(await workflowsApi.execution(id)); } catch (err) { setError(err instanceof Error ? err.message : 'Workflow execution is unavailable.'); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  if (error) return <div className="mx-auto w-full max-w-4xl"><ErrorState message={error} onRetry={() => void load()} /></div>;
  if (!data) return <Loading detail />;
  const { execution, steps } = data; const outcome = execution.status === 'succeeded' ? 'Workflow completed successfully.' : execution.status === 'failed' ? (execution.failure_message || 'Workflow failed.') : execution.status === 'running' || execution.status === 'pending' ? 'Workflow is still processing.' : 'Outcome unavailable.';
  const leadCompleted = steps.find(step => step.action_type === 'bavio.lead.create' && step.status === 'succeeded');
  return <div className="mx-auto w-full max-w-4xl space-y-9"><Link href={workflowPath(execution.workflow_definition_id)} className="inline-flex items-center gap-2 text-xs font-semibold text-ink-secondary hover:text-ink"><ArrowRight className="rotate-180" size={15} />{execution.name}</Link><header className="border-b border-line pb-7"><span className="font-mono text-[10px] uppercase tracking-[0.18em] text-ink-tertiary">Workflow run</span><div className="mt-3 flex flex-wrap items-center gap-3"><h1 className="font-display text-3xl font-extrabold tracking-tight text-ink md:text-4xl">{execution.name}</h1><Status status={execution.status} /></div><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-xs text-ink-secondary"><span>Version {execution.version}</span><span>{formatDate(execution.started_at || execution.created_at)}</span>{displaySource(execution) && <span>{displaySource(execution)}</span>}</div></header><section aria-labelledby="execution-trace-heading" className="space-y-5"><div><h2 id="execution-trace-heading" className="text-xs font-bold uppercase tracking-[0.16em] text-ink">Execution trace</h2><p className="mt-1 text-xs text-ink-tertiary">Workflow → Step → Action execution → Evidence</p></div><div className="relative ml-1 border-l border-line pl-9">{steps.map((step, index) => <TraceStep key={step.id} step={step} previousStepName={index > 0 ? steps[index - 1].name : undefined} />)}</div></section>{leadCompleted && execution.status === 'failed' && <section className="border-y border-line py-5"><span className="font-mono text-[9px] uppercase tracking-wider text-ink-muted">Completed effect</span><p className="mt-1 text-sm text-ink">Lead created in Bavio</p></section>}<section className="grid gap-5 border-y border-line py-6 sm:grid-cols-3"><div><span className="font-mono text-[9px] uppercase tracking-wider text-ink-muted">Outcome</span><p className="mt-1 text-sm text-ink">{outcome}</p></div><div><span className="font-mono text-[9px] uppercase tracking-wider text-ink-muted">Started</span><p className="mt-1 text-sm text-ink">{formatDate(execution.started_at || execution.created_at)}</p></div><div><span className="font-mono text-[9px] uppercase tracking-wider text-ink-muted">Completed</span><p className="mt-1 text-sm text-ink">{formatDate(execution.completed_at)}</p></div></section>{execution.failure_code && <p className="flex items-start gap-2 text-xs text-ink-muted"><Warning size={15} className="mt-0.5 shrink-0" />Technical details · {execution.failure_code}</p>}</div>;
}
