"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowRight, ArrowUpRight, BookOpen, Check, Phone, Sparkle, Users } from "@phosphor-icons/react";
import { assistantsApi, callsApi, knowledgeBaseApi, numbersApi, getClientId, type Assistant, type CallRecord, type KnowledgeDoc, type PhoneNumber } from "@/lib/api";
import { useWorkspace } from "@/context/WorkspaceContext";

type LoadState = "loading" | "ready" | "failed";
const time = (value?: string | null) => value ? new Date(value).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" }) : "Time unavailable";
function Status({ children, tone = "muted" }: { children: React.ReactNode; tone?: "complete" | "accent" | "muted" }) { return <span className={`workspace-status workspace-status-${tone}`}><span aria-hidden="true" />{children}</span>; }

export default function WorkspaceHome() {
  const { profile, isProfileLoading, profileError } = useWorkspace();
  const clientId = getClientId();
  const [assistants, setAssistants] = useState<Assistant[]>([]), [calls, setCalls] = useState<CallRecord[]>([]), [numbers, setNumbers] = useState<PhoneNumber[]>([]), [knowledge, setKnowledge] = useState<KnowledgeDoc[]>([]), [dataState, setDataState] = useState<LoadState>("loading");
  const load = useCallback(async () => { if (!clientId) { setDataState("failed"); return; } setDataState("loading"); try { const [agents, conversations, phoneNumbers, sources] = await Promise.all([assistantsApi.list(clientId), callsApi.list(clientId), numbersApi.list(clientId), knowledgeBaseApi.list()]); setAssistants(Array.isArray(agents) ? agents : []); setCalls(Array.isArray(conversations) ? conversations : []); setNumbers(Array.isArray(phoneNumbers) ? phoneNumbers : []); setKnowledge(Array.isArray(sources) ? sources : []); setDataState("ready"); } catch { setDataState("failed"); } }, [clientId]);
  useEffect(() => { void load(); }, [load]);
  if (isProfileLoading || dataState === "loading") return <main className="workspace-overview"><p role="status">Loading workspace…</p></main>;
  if (profileError || dataState === "failed" || !profile) return <main className="workspace-overview"><section className="workspace-error" role="alert"><h1>Workspace unavailable</h1><p>Workspace information could not be loaded.</p><button onClick={() => void load()}>Retry</button></section></main>;
  const ready = assistants.length > 0 && knowledge.length > 0 && numbers.length > 0;
  const activity = [...calls].sort((a, b) => Date.parse(b.created_at) - Date.parse(a.created_at)).slice(0, 5);
  const phoneValue = profile.twilio_number || (numbers.length ? numbers[0].number : null);
  const setupSteps = [["Business profile", Boolean(profile.name && profile.industry), "/workspace/settings", "Add the details your agent should know."], ["Create agent", assistants.length > 0, "/dashboard/assistant", "Define the voice and instructions."], ["Add knowledge", knowledge.length > 0, "/dashboard/knowledge", "Give Bavio your business information."], ["Voice & language", assistants.some(agent => Boolean(agent.voice || agent.language)), "/dashboard/assistant", "Choose a real available voice."], ["Phone number", Boolean(phoneValue), "/dashboard/phone-numbers", "Connect a line when you are ready."], ["Test agent", calls.length > 0, "/dashboard/assistant", "Run a model behavior test."]] as const;
  return <main className="workspace-overview" aria-labelledby="workspace-overview-title">
    <header className="workspace-overview-header"><div><span className="workspace-kicker">Workspace overview</span><h1 id="workspace-overview-title">{ready ? `Welcome back, ${profile.name || "Workspace"}` : "Let’s get Bavio ready"}</h1><p>Configure your workspace, review activity, and keep operations moving.</p></div><div className="workspace-header-actions"><button className="workspace-refresh" onClick={() => void load}>Refresh</button><Link className="workspace-primary" href="/workspace/demo"><Sparkle size={15} />Try web call</Link></div></header>
    <section className="workspace-status-strip" aria-label="Workspace status"><div><span>System</span><strong>Unavailable</strong></div><div><span>Agents</span><strong>{assistants.length} configured</strong></div><div><span>Conversations</span><strong>{calls.length ? `${calls.length} recorded` : "0 recorded"}</strong></div><div><span>Talk time</span><strong>Unavailable</strong></div><div><span>Phone</span><strong>{phoneValue || "Not connected"}</strong></div></section>
    {!ready && <section className="workspace-setup" aria-labelledby="setup-title"><div className="workspace-section-heading"><div><span className="workspace-kicker">Get Bavio ready</span><h2 id="setup-title">A short path to your first live workflow</h2></div><span className="workspace-muted">{setupSteps.filter(step => step[1]).length} of {setupSteps.length} complete</span></div><ol className="workspace-stepper">{setupSteps.map(([label, complete, href, description], index) => { const current = !complete && !setupSteps.slice(0, index).some(step => !step[1]); return <li key={label} className={complete ? "is-complete" : current ? "is-current" : ""}><span className="workspace-step-marker">{complete ? <Check size={14} /> : String(index + 1).padStart(2, "0")}</span><Link href={href}><span><strong>{label}</strong><small>{description}</small></span><Status tone={complete ? "complete" : current ? "accent" : "muted"}>{complete ? "Complete" : current ? "Next" : "Not configured"}</Status><ArrowRight size={15} aria-hidden="true" /></Link></li>; })}</ol></section>}
    <div className="workspace-columns"><section className="workspace-section" aria-labelledby="activity-title"><div className="workspace-section-heading"><div><span className="workspace-kicker">Recent activity</span><h2 id="activity-title">What happened next</h2></div><Link href="/dashboard/calls" className="workspace-text-link">View conversations <ArrowUpRight size={14} /></Link></div>{activity.length ? <div className="workspace-activity">{activity.map(call => <Link href={`/dashboard/calls/${encodeURIComponent(call.id)}`} key={call.id}><time>{time(call.created_at)}</time><span aria-hidden="true" /><p>Conversation {call.call_status || "status unavailable"}<small>{call.caller_number || "Caller unavailable"}</small></p><ArrowRight size={15} /></Link>)}</div> : <div className="workspace-empty"><h3>No activity yet</h3><p>Your conversations and verified actions will appear here.</p></div>}</section><section className="workspace-section" aria-labelledby="infrastructure-title"><div className="workspace-section-heading"><div><span className="workspace-kicker">Workspace infrastructure</span><h2 id="infrastructure-title">Connected services</h2></div></div><div className="workspace-register"><div><span>Telephony</span><Status tone={phoneValue ? "complete" : "muted"}>{phoneValue ? "Configured" : "Not configured"}</Status></div><div><span>Voice</span><Status tone={assistants.some(agent => Boolean(agent.voice)) ? "complete" : "muted"}>{assistants.some(agent => Boolean(agent.voice)) ? "Configured" : "Unable to verify"}</Status></div><div><span>Knowledge</span><Status>{knowledge.length} sources</Status></div></div></section></div>
    <div className="workspace-columns workspace-columns-bottom"><section className="workspace-section" aria-labelledby="profile-title"><div className="workspace-section-heading"><div><span className="workspace-kicker">Workspace</span><h2 id="profile-title">Profile at a glance</h2></div><Link href="/workspace/settings" className="workspace-text-link">Settings <ArrowUpRight size={14} /></Link></div><div className="workspace-profile-rows"><div><span>Name</span><strong>{profile.name || "Workspace unavailable"}</strong></div><div><span>Phone</span><strong>{phoneValue || "Not connected"}</strong></div><div><span>Knowledge</span><strong>{knowledge.length} sources</strong></div></div></section><section className="workspace-section" aria-labelledby="plan-title"><div className="workspace-section-heading"><div><span className="workspace-kicker">Plan & usage</span><h2 id="plan-title">Account state</h2></div><Link href="/workspace/subscription" className="workspace-text-link">Manage billing <ArrowUpRight size={14} /></Link></div><div className="workspace-profile-rows"><div><span>Current plan</span><strong>{profile.plan_name === "internal_qa_starter" ? "Starter — Internal QA" : (profile.plan_name || "Unavailable")}</strong></div><div><span>Usage</span><strong>Unavailable</strong></div></div></section></div>
    <nav className="workspace-actions" aria-label="Quick actions"><Link href="/dashboard/assistant"><Users size={16} />Create agent</Link><Link href="/dashboard/phone-numbers"><Phone size={16} />Connect number</Link><Link href="/dashboard/knowledge"><BookOpen size={16} />Add knowledge</Link><Link href="/workspace/demo"><Sparkle size={16} />Try web call</Link><Link href="/dashboard/calls"><ArrowRight size={16} />View conversations</Link></nav>
  </main>;
}
