-- Create enum for business plans
CREATE TYPE business_plan AS ENUM ('basic', 'pro', 'enterprise');
-- Create enum for business status
CREATE TYPE entity_status AS ENUM ('active', 'inactive', 'suspended');

-- 1. Businesses Table
CREATE TABLE businesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_name VARCHAR(255) NOT NULL,
    owner_name VARCHAR(255) NOT NULL,
    owner_email VARCHAR(255) UNIQUE NOT NULL,
    owner_phone VARCHAR(50) NOT NULL,
    plan business_plan DEFAULT 'basic',
    status entity_status DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- 2. Assistants Table
CREATE TABLE assistants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT REFERENCES businesses(id) ON DELETE CASCADE,
    assistant_name VARCHAR(255) NOT NULL,
    language VARCHAR(50) DEFAULT 'en',
    industry VARCHAR(100),
    first_message TEXT,
    system_prompt TEXT,
    status entity_status DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- 4. Exotel Pools Table (needs to be created before phone_numbers for foreign key)
CREATE TABLE exotel_pools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exotel_number VARCHAR(50) UNIQUE NOT NULL,
    max_concurrent_calls INTEGER DEFAULT 50,
    active_customers INTEGER DEFAULT 0,
    status entity_status DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- 3. Phone Numbers Table
CREATE TABLE phone_numbers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT REFERENCES businesses(id) ON DELETE CASCADE,
    original_number VARCHAR(50) UNIQUE NOT NULL,
    forwarding_enabled BOOLEAN DEFAULT false,
    verification_status VARCHAR(50) DEFAULT 'pending',
    exotel_pool_id BIGINT REFERENCES exotel_pools(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- 5. Call Sessions Table
CREATE TABLE call_sessions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    business_id BIGINT REFERENCES businesses(id) ON DELETE CASCADE,
    call_sid VARCHAR(255) UNIQUE NOT NULL,
    caller_number VARCHAR(50) NOT NULL,
    original_number VARCHAR(50) NOT NULL,
    session_status VARCHAR(50) DEFAULT 'in-progress',
    started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
    ended_at TIMESTAMP WITH TIME ZONE
);

-- 6. Calls Table
CREATE TABLE calls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    call_sid VARCHAR(255) UNIQUE REFERENCES call_sessions(call_sid) ON DELETE CASCADE,
    business_id BIGINT REFERENCES businesses(id) ON DELETE CASCADE,
    duration_seconds INTEGER,
    cost DECIMAL(10, 4),
    status VARCHAR(50) DEFAULT 'completed',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- 7. Transcripts Table
CREATE TABLE transcripts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    call_sid VARCHAR(255) REFERENCES call_sessions(call_sid) ON DELETE CASCADE,
    role VARCHAR(50) NOT NULL, -- 'user' or 'assistant'
    content TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- 8. Leads Table
CREATE TABLE leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT REFERENCES businesses(id) ON DELETE CASCADE,
    call_sid VARCHAR(255) REFERENCES call_sessions(call_sid) ON DELETE CASCADE,
    caller_name VARCHAR(255),
    caller_phone VARCHAR(50),
    intent VARCHAR(255),
    summary TEXT,
    extracted_data JSONB,
    status VARCHAR(50) DEFAULT 'new',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- 9. Usage Logs Table
CREATE TABLE usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT REFERENCES businesses(id) ON DELETE CASCADE,
    service_type VARCHAR(100), -- 'sarvam_stt', 'sarvam_llm', 'exotel_call'
    quantity INTEGER,
    cost DECIMAL(10, 4),
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- 10. Notifications Table
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT REFERENCES businesses(id) ON DELETE CASCADE,
    type VARCHAR(50), -- 'whatsapp', 'email'
    recipient VARCHAR(255),
    content TEXT,
    status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Indexes for fast routing and querying
CREATE INDEX idx_phone_numbers_original_number ON phone_numbers(original_number);
CREATE INDEX idx_call_sessions_call_sid ON call_sessions(call_sid);
CREATE INDEX idx_businesses_id ON businesses(id);
CREATE INDEX idx_exotel_pools_exotel_number ON exotel_pools(exotel_number);
CREATE INDEX idx_transcripts_call_sid ON transcripts(call_sid);
CREATE INDEX idx_leads_business_id ON leads(business_id);
