import { useState } from 'react';
import Link from 'next/link';
import type { Draft, Voice } from './service';
import type { PhoneNumber } from '@/lib/api';
import s from './agents.module.css';

export const sections = [ ['identity', 'Behavior', 'Identity'], ['instructions', 'Behavior', 'Instructions'], ['knowledge', 'Intelligence', 'Knowledge'], ['voice', 'Conversation', 'Voice & language'], ['deployment', 'Deploy', 'Phone assignment'], ['test', 'Quality', 'Test'] ] as const;
export type Section = typeof sections[number][0];
interface Props { section: Section; draft: Draft; set: (key: keyof Draft, value: string | boolean) => void; creating: boolean; voices: Voice[]; voiceError: boolean; knowledgeCount: number | null; numbers: PhoneNumber[]; numberError: boolean; assigned: string; }

const starterTemplate = 'You are the AI receptionist for [Business]. Your responsibilities are…';

export default function AgentFields(p: Props) {
  const [nameTouched, setNameTouched] = useState(false);
  const { draft: d, set } = p;
  const nameInvalid = (nameTouched && !d.name.trim()) || d.name.length > 120;
  const selectedVoice = p.voiceError || d.voice_id.startsWith('local-preview-') ? '' : d.voice_id;
  return <div className={s.fields}>
    {p.section === 'identity' && <><span className={s.eyebrow}>Behavior</span><h2>Who this agent is</h2><p>Configure how this agent represents your business.</p><label htmlFor="agent-name">Agent name<span className={s.helper}>Use a clear name your team will recognize.</span><input id="agent-name" required maxLength={120} value={d.name} onBlur={() => setNameTouched(true)} aria-invalid={nameInvalid} onChange={e => set('name', e.target.value)} autoComplete="off" aria-describedby="agent-name-help" /></label><small id="agent-name-help" className={s.fieldMeta}>{nameInvalid ? 'Enter an agent name between 1 and 120 characters. ' : ''}{d.name.length}/120 characters</small>{!p.creating && <><label htmlFor="agent-greeting">Greeting<textarea id="agent-greeting" rows={3} value={d.greeting} onChange={e => set('greeting', e.target.value)} /></label><label className={s.check}><input type="checkbox" checked={d.is_active} onChange={e => set('is_active', e.target.checked)} />Enable agent configuration</label><p>Enables this agent configuration. Phone service is managed separately.</p></>}</>}
    {p.section === 'instructions' && <><span className={s.eyebrow}>Behavior</span><h2>How this agent should behave</h2><p>Set responsibilities, tone, and boundaries for each response.</p>{!d.system_prompt.trim() && <div className={s.starter}><strong>Start with a clear brief</strong><p>Suggested starter: “{starterTemplate}”</p><button type="button" onClick={() => { set('system_prompt', starterTemplate); document.getElementById('agent-instructions')?.focus(); }}>Insert starter template</button></div>}<label htmlFor="agent-instructions">Instructions<textarea id="agent-instructions" className={s.editor} required value={d.system_prompt} onChange={e => set('system_prompt', e.target.value)} spellCheck aria-describedby="instructions-help" /></label><div id="instructions-help" className={s.guidance}><strong>Include guidance on:</strong><ul><li>role and responsibilities</li><li>tone and boundaries</li><li>when to escalate</li><li>questions it cannot answer</li></ul></div><div className={s.editorFooter}><small>{d.system_prompt.length.toLocaleString()} characters</small><small>Write the rules this agent should follow.</small></div></>}
    {p.section === 'knowledge' && <><span className={s.eyebrow}>Intelligence</span><h2>Workspace knowledge</h2><p>Knowledge is managed at workspace level.</p><p>{p.knowledgeCount === null ? 'Knowledge unavailable.' : `${p.knowledgeCount} sources available`}</p><Link href="/dashboard/knowledge">Manage knowledge →</Link></>}
    {p.section === 'voice' && <><span className={s.eyebrow}>Conversation</span><h2>Voice & language</h2><p>How this agent communicates.</p><label htmlFor="agent-voice">Selected voice<select id="agent-voice" value={selectedVoice} disabled={p.voiceError} onChange={e => set('voice_id', e.target.value)}>{p.voiceError ? <option value="">Voice service unavailable</option> : <><option value="">Select a voice</option>{p.voices.map(v => <option key={v.voice_id} value={v.voice_id}>{v.voice_display_name} · {v.voice_language}</option>)}</>}</select></label>{p.voiceError && <p role="status">Voice service unavailable</p>}<label htmlFor="agent-language">Primary language<select id="agent-language" value={d.language} onChange={e => set('language', e.target.value)}>{!['en-US','hi-IN'].includes(d.language) && <option value={d.language}>{d.language} (stored language)</option>}<option value="en-US">English</option><option value="hi-IN">Hindi</option></select></label><p>Open Test to hear a preview when one is available.</p></>}
    {p.section === 'deployment' && <><span className={s.eyebrow}>Deploy / voice</span><h2>Phone assignment</h2><p>Route incoming calls from a workspace number to this agent.</p>{p.creating ? <p>No number assigned. Create the agent before assigning a number.</p> : p.numberError ? <p role="status">Phone assignment unavailable.</p> : <><div><strong>Assigned number</strong><p>{p.numbers.find(n => n.id === p.assigned)?.number || 'No number assigned'}</p></div></>}<Link href="/dashboard/phone-numbers">Manage phone numbers →</Link></>}
  </div>;
}
